### ISSUE TITLE
Compatibility with Python 3 and Nuke 13?

### ISSUE THREAD

**Issue by okfineIGitIt** [ThoriumGroup/animatedSnap3D#7]
Looking to use this package in Nuke 13, which ships with Python 3. Are there any plans to extend compatibility to Python 3?

**Comment by okfineIGitIt** [comment]
@shidarin @ivanbusquets Hi, just want to check that this issue is reaching you. I was wondering whether you guys intend to make a python-3.7 compatible release of this package now that nuke-13 is out?

**Comment by shidarin** [comment]
I got the issue @okfineIGitIt , but unfortunately I don't currently have any time to maintain or upgrade this stuff. I was about to archive all the repositories and the group itself.

**Comment by okfineIGitIt** [comment]
Alright, understood. @shidarin In that case do you mind accepting a PR for this issue? I need this package for work and am willing to update and test it myself.

**Comment by shidarin** [comment]
Absolutely. 2to3 should get you pretty far

**Comment by herronelou** [comment]
@shidarin I'm going to put a PR soon, but I was wondering what spec you're following for the docstrings, it looks close to Google style but not quite?

**Comment by shidarin** [comment]
Closed with PR #8
